import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./reset.css";
import "./globals.css";

import Header from "@/front-end/components/layouts/Header/Header";
import {DataTime} from "@/front-end/components/ui/DataTime/DataTime";
import ActionBar from "@/front-end/components/layouts/ActionBar/ActionBar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
      <ActionBar/>
      <Header/>
        {children}
      <DataTime/>
      </body>
    </html>
  );
}
